### ISSUE TITLE
Area of Square is missing

### ISSUE THREAD

**Issue by GhanashyamKadam** [wbhoomika/python4beginners-Hacktoberfest23#14]
Area of Square is missing in the area_calculator.py

**Comment by vinay1033** [comment]
I can resolve issue by contributing in your code.

**Comment by Tanay3484** [comment]
I would like to add a feature to the area_calculator.py file by adding functions to calculate the area of a few more shapes. Can I work on the same?

**Comment by wbhoomika** [comment]
sure please.
