### ISSUE TITLE
This repo excluded from HackOctoberfest :(

### ISSUE THREAD

**Issue by Anu27n** [wbhoomika/python4beginners-Hacktoberfest23#93]

**Comment by wbhoomika** [comment]
Yes maybe because some contributors submitted plagiarize code and it violated their values. :(
However I created a new repo: https://github.com/wbhoomika/portfolio-template-Hacktoberfest23. Feel free to contribute.

**Comment by Anu27n** [comment]
Sad to here bhoomika i hope the new repo dont fall into this again
